# Generated by Django 3.1.7 on 2021-04-16 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('text', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('title', models.CharField(max_length=40, verbose_name='title')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('title', models.CharField(max_length=40, verbose_name='title')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('name', models.CharField(max_length=40, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('title', models.CharField(max_length=40, verbose_name='title')),
                ('description', models.TextField(blank=True)),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'feature'), (2, 'bug')], null=True, verbose_name='type')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'created'), (2, 'active'), (3, 'completed'), (4, 'rejected'), (5, 'void')], null=True, verbose_name='status')),
                ('priority', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'low'), (2, 'medium'), (3, 'high')], null=True, verbose_name='priority')),
                ('Epic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.epic')),
                ('comments', models.ManyToManyField(to='tasks.Comment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('linked_tasks', models.ManyToManyField(related_name='_task_linked_tasks_+', to='tasks.Task')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_orders', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project')),
                ('tags', models.ManyToManyField(to='tasks.Tag')),
            ],
        ),
    ]
