# Generated by Django 3.1.7 on 2021-04-16 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20210416_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='tasks.Comment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='linked_tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='_task_linked_tasks_+', to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owners',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tasks.Tag'),
        ),
    ]
